### ISSUE TITLE
API Requirement

### ISSUE THREAD

**Issue by suryanadiminti99** [universewill/FloorPlanParser#1]
Hi , What is the price ? I am unable to send mail to your given mail Id. Please check it once get back to me. 
suryanadiminti99@gmail.com

**Comment by thrishool0145** [comment]
Hi, I mailed to univese.will@gmail.com . But it's showing invalid. Can you please check and get back on thrishool0145@gmail.com

**Comment by universewill** [comment]
@suryanadiminti99 @thrishool0145
Hey， my email is universe.will@gmail.com

visit demo page to see if the result is what you need:
http://192.168.31.61:9595/floor_plan_parser_demo
